{
 "title": "Chain Dashboard",
 "description": "A Grafana dashboard compatible with all the cosmos-sdk and tendermint based blockchains.",
 "tags": [
  "Blockchain",
  "Cosmos",
  "Crypto.org",
  "Cronos"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": "label_values(tendermint_consensus_height, chain_id)"
   },
   {
    "name": "role",
    "label": "Role:",
    "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, role)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\", role=\"$role\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$chain_id overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4.8, "x": 0, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4.8, "x": 4.8, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3.6, "x": 13.2, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rate(tendermint_consensus_block_interval_seconds_sum{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}[1m])/rate(tendermint_consensus_block_interval_seconds_count{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}[1m]))"
    }
   ]
  },
  {
   "title": "Missing validators",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3.5, "x": 16.8, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(tendermint_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"})"
    }
   ]
  },
  {
   "title": "Bonded Tokens",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3.6, "x": 20.3, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators_power{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}",
     "legendFormat": "Mempool Size"
    }
   ]
  },
  {
   "title": "Round",
   "type": "graph",
   "description": "tendermint_consensus_rounds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_rounds{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}",
     "legendFormat": "Round"
    }
   ]
  },
  { "title": "instance overview: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "instance" },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_mempool_failed_txs{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Recheck Times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 28 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_mempool_recheck_times{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Network Input",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_p2p_peer_receive_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total Network Output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_p2p_peer_send_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\", role=\"$role\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}